[package]
name = "wheel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
figlet-rs = "0.1.3"
rainbowcoat = "0.1.0"
